sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t alastairhm/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alastairhm/docker-react npm run test