sudo: required
language: generic
services:
  - docker

before_install:
  - docker login --username "$DOCKER_USER" --password "$DOCKER_PASSWORD"
  - docker build -t alastairhm/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alastairhm/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-139746160101"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
